site_name: './infwiki'
site_description: 'El repositorio de conocimiento de Informática UdeC'
site_author: 'Mr. Alcerson'
docs_dir: docs/
repo_name: 'mhausenblas/actions-sandbox'
repo_url: 'https://github.com/mhausenblas/actions-sandbox'
nav:
    - '¡Bienvenido a Infwiki!': 'index.md'
theme:
  name: 'material'
  logo: assets/logo.png
  language: es
  palette:
    scheme: slate
    primary: blue
    accent: amber
  font:
    text: Fira Sans
    code: Fira Mono
plugins:
  - search
  - git-revision-date
markdown_extensions:
  - footnotes
  - attr_list
